backend:
  name: git-gateway
  branch: main
collections:
  - name: "class" # Used in routes, e.g., /admin/collections/blog
    label: "Class" # Used in the UI
    folder: "classes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
